export const CSSClasses = {
	EDITOR: 'nc-editor',
	TEXT_LAYER: 'nc-editor__text',
	GUTTER: 'nc-editor__gutter',
	GUTTER_NUMBER: 'nc-gutter__number',
	MAIN_INPUT: 'nc-editor__input',
	CURSOR: 'nc-selection__cursor',
	CURSOR_ANIMATED: 'nc-selection__cursor--animated',
	MULTI_LINE: 'nc-text__multi-line',
	MULTI_LINE_ACTIVE: 'nc-text__multi-line--active',
	MULTI_LINE_HOVERED: 'nc-text__multi-line--hovered',
	MULTI_LINE_CONTENT: 'nc-text__multi-line_content',
	SELECTION_RANGE: 'nc-selection__range',
	SELECTION_SEARCH: 'nc-selection__search',
	SELECTION_SEARCH_ACTIVE: 'nc-selection__search--active',
	SELECTION: 'nc-editor__selection',
	SCROLL_BAR: 'nc-editor__scroll-bar',
	SCROLL_INNER: 'nc-scroll__scrollable',
	SEARCH: 'nc-search',
	CLOSE_SEARCH: 'nc-search__close',
	SEARCH_INPUT: 'nc-search__input',
	SEARCH_RESULT: 'nc-search__result',
};
