import EdiotrView from './editor-view';
import { SelectionLayerEvents } from './events';
import { EventEmitter } from '../events';
export default class SelectionLayer extends EventEmitter<SelectionLayerEvents> {
    private _emitterName;
    private _view;
    private _mountPoint;
    private _selectionContainer;
    private _firstVisibleLine;
    private _visibleLinesCount;
    private _lineHeight;
    private _letterWidth;
    private _visibleSelections;
    private _isMouseHold;
    private _isTouchHold;
    private _isTouchSelecting;
    private _isCtrlHold;
    private _isShitHold;
    private _isAltHold;
    private _lastTouchTime;
    private _lastTouchPosition;
    private _showSearchResults;
    constructor(view: EdiotrView);
    private get _session();
    setFirstVisibleLine(firstLine: number): void;
    setVisibleLinesCount(linesCount: number): void;
    update(): void;
    private _crateSelctionContainer;
    private _initEventListeners;
    private _renderSelections;
    private _renderCursors;
    private _renderSearchResults;
    private _onMouseDown;
    private _onMouseUp;
    private _onMouseMove;
    private _onDoubleClick;
    private _onTouchStart;
    private _onTouchEnd;
    private _onTouchMove;
    private _getLineAndOffsetAtPosition;
}
