import { EventEmitter } from '../events';
import EdiotrView from './editor-view';
import { SearchUiEvents } from './events';
declare class EditorSearch extends EventEmitter<SearchUiEvents> {
    private _view;
    private _mountPoint;
    private _searchContainer;
    private _closeButton;
    private _nextResultButton;
    private _prevResultButton;
    private _caseSensitiveToggleButton;
    private _regexToggleButton;
    private _selectionSearchToggleButton;
    private _replaceButton;
    private _replaceAllButton;
    private _input;
    private _replaceInput;
    private _resultsContainer;
    private _isOpen;
    private _seatchMatchesCount;
    private _searchPhrase;
    private _regexpSearch;
    private _caseSensitiveSearch;
    private _selectionSearch;
    constructor(view: EdiotrView);
    private get _session();
    update(): void;
    show(): void;
    hide(): void;
    getDOMElement(): HTMLDivElement | null;
    private _search;
    private _initEventListeners;
    private _setCaseSensitiveSearch;
    private _setSelectionSearch;
    private _setRegExpSearch;
    private _createSearchContainer;
}
export default EditorSearch;
