export declare const CSSClasses: {
    EDITOR: string;
    TEXT_LAYER: string;
    GUTTER: string;
    GUTTER_NUMBER: string;
    GUTTER_NUMBER_ACTIVE: string;
    MAIN_INPUT: string;
    CURSOR: string;
    CURSOR_ANIMATED: string;
    MULTI_LINE: string;
    MULTI_LINE_ACTIVE: string;
    MULTI_LINE_HOVERED: string;
    MULTI_LINE_CONTENT: string;
    SELECTION_RANGE: string;
    SELECTION_SEARCH: string;
    SELECTION_SEARCH_ACTIVE: string;
    SELECTION: string;
    SCROLL_BAR: string;
    SCROLL_INNER: string;
    SEARCH: string;
    CLOSE_SEARCH: string;
    SEARCH_INPUT: string;
    SEARCH_RESULT: string;
};
